### ISSUE TITLE
Questions on NCLSolve

### ISSUE THREAD

**Issue by dpo** [PEPERSO/NCL#3]
I have a few questions on the NCLSolve function:

* why are tau, alpha, beta and rho Float32 variables?
* the name `Type` is reserved; we should not use it as a variable name;
* the line `Type::DataType = typeof(ncl.meta.x0[1])` should be `dtype = eltype(ncl.meta.x0)`;
* it is not necessary to declare the type of each variable. Julia will know when you give it a value. However, it's important to not change the type of a variable within a function. So `acc_count::Int64 = 0` should just be `acc_count = 0`.

More comments later...

**Comment by PEPERSO** [comment]
- I put them in Float32 because they don't need Float64 precision, so it uses less memory, but it doesn't really matters to me

- Okay, I didn't know about ```eltype```(), I will change that

- I know it is not necessary, but I declared them to be sure to be type consistent...

**Comment by dpo** [comment]
I changed it all in #1.
